version: '3.8'
services:
  exam-potgres:
    container_name: exam-potgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_UER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5433"
    volumes:
      - exam-potgres-volume:/var/lib/postgresql/data
volumes:
  cowork-potgres-volume:
      